"""empty message

Revision ID: 87e469e6a98e
Revises: 7490eb62b9c1
Create Date: 2024-06-24 14:55:51.224097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87e469e6a98e'
down_revision: Union[str, None] = '7490eb62b9c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('menu', sa.Column('name_to_get', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'name_to_get')
    op.drop_table('admins')
    # ### end Alembic commands ###
